# Configuration specific to the application service. All fields (unless otherwise marked) are required.
homeserver:
  # The domain for the client-server API calls.
  url: "http://localhost:8008"

  # The domain part for user IDs on this home server. Usually, but not always, this is the same as the
  # home server's URL.
  domain: "localhost"

  # The URL of the homeserver hosting media files. This is only used to transform uploaded content to
  # messages for bridged users. If not specified, the `url` for the client-server API is used.
  #mediaUrl: "http://localhost:8008"

# Configuration specific to the bridge. All fields (unless otherwise marked) are required.
mcBridge:
  # The credentials to the Mojang account with Minecraft purchased. These credentials are used when the
  # bridge doesn't have a plugin it can use on the Minecraft server to bridge chat.
  mojangAccount:
    username: "myemail@example.com"
    password: "MySecretPassw0rd"