# Configuration specific to the application service. All fields (unless otherwise marked) are required.
homeserver:
  # The domain for the client-server API calls.
  url: "http://localhost:8008"

  # The domain part for user IDs on this home server. Usually, but not always, this is the same as the
  # home server's URL.
  domain: "localhost"

# Configuration specific to the bridge. All fields (unless otherwise marked) are required.
mcBridge:
  # The credentials to the Mojang account with Minecraft purchased. These credentials are used when the
  # bridge doesn't have a plugin it can use on the Minecraft server to bridge chat.
  mojangAccount:
    username: "myemail@example.com"
    password: "MySecretPassw0rd"

  # Appearance options for the Matrix bot
  appearance:
    displayName: "Minecraft Bridge"
    avatarUrl: "http://i.imgur.com/ELbV0Af.png" # grass block

logging:
  file: logs/minecraft.log
  console: true
  consoleLevel: info
  fileLevel: verbose
  rotate:
    size: 52428800 # bytes, default is 50mb
    count: 5